{
 "title": "Services statistic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payment Retry Count (30s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(payment_external_retry_count_total[30s])) by (accountName)",
       "legendFormat": "{{accountName}}"
      }
     ]
    },
    {
     "title": "Payments outcome rate per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(payment_finished_total{service=~\"$service\"}[30s])) by (service, outcome, failReason)",
       "legendFormat": "{{outcome}} - {{failReason}}"
      }
     ]
    },
    {
     "title": "Event during testing per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (type) (rate(events_total{}[30s]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tests run",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(test_duration_count{service=~\"$service\"}[$__range])) by (service, testOutcome)",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    },
    {
     "title": "Success percent (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by(service)(increase(test_duration_count{service=~\"$service\", testOutcome=~\"SUCCESS\"}[1m]))) / (sum by(service) (increase(test_duration_count{service=~\"$service\", testOutcome=~\".*\"}[1m])))",
       "legendFormat": "{{service}} - success"
      }
     ]
    },
    {
     "title": "Average test duration by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(test_duration_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (rate(test_duration_count{service=~\"$service\"}[1m]))",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Fail stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"failed\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Success stages duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(stage_duration_ok_sum{service=~\"$service\", result=\"success\"}[1m]) / rate(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Http calls info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "(Clients -> Online shop) http requests processed rate (rps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_external_duration_count{service=~\"$service\"}[30s])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "(Clients -> Online shop) http requests duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(http_external_duration_sum{service=~\"$service\"}[1m]) / rate(http_external_duration_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{method}} - {{result}}"
      }
     ]
    },
    {
     "title": "(Online shop -> Payment system)  http requests processed rate (rps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(external_sys_duration_count{service=~\"$service\"}[30s])",
       "legendFormat": "{{accountName}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "(Online shop -> Payment system)  Payment sys processing duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(external_sys_duration_sum{service=~\"$service\"}[1m]) / rate(external_sys_duration_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{accountName}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "(Test system -> Online shop)  Average request latent time (before submit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_latent_sum{service=~\"$service\"}[15s]) / rate(http_request_latent_count{service=~\"$service\"}[15s]))",
       "legendFormat": "{{method}} - {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "max by (name) (executor_queued_tasks{service=~\"$service\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Completed tasks rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by (name) (rate(executor_completed_tasks_total{}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Active executors threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "sum by (name) (executor_active_threads{})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage (XMX%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum ((sum by (job, area) (jvm_memory_used_bytes{area=\"heap\"}) / sum by (job, area) (jvm_memory_max_bytes{area=\"heap\"})) * 100) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (jvm_threads_live_threads{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (process_files_open_files{})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_max{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Thread Config Min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_min{service=~\"$service\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Jetty Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_busy{})",
       "legendFormat": "{{job}} -  busy "
      },
      {
       "expr": "sum by (job) (jetty_threads_idle{})",
       "legendFormat": "{{job}} - idle"
      },
      {
       "expr": "sum by (job) (jetty_threads_current{})",
       "legendFormat": "{{job}} - current"
      },
      {
       "expr": "sum by (job) (jetty_threads_jobs{})",
       "legendFormat": "{{job}} - jobs"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{service=~\"$service\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (job, method, status, uri) (irate(http_server_requests_seconds_sum{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}} - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Payment Processing - Active Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "История задач в очереди",
     "type": "timeseries",
     "description": "История изменения количества задач в очереди",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "payment_processing_planned_total - payment_processing_started_total",
       "legendFormat": "{{accountName}}"
      }
     ]
    },
    {
     "title": "Throughput (в очереди vs в обработке vs обработаны)",
     "type": "timeseries",
     "description": "Скорость входа в ожидание и выхода из ожидания (requests/sec)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(payment_processing_planned_total[1m])",
       "legendFormat": "Попало в очередь: {{accountName}}"
      },
      {
       "expr": "rate(payment_processing_started_total[1m])",
       "legendFormat": "Приняты в обработку (вышли из очереди): {{accountName}}"
      },
      {
       "expr": "rate(payment_processing_completed_total[1m])",
       "legendFormat": "Обработаны: {{accountName}}"
      }
     ]
    },
    {
     "title": "Скорость накопления задач (увеличения очереди)",
     "type": "timeseries",
     "description": "Если значение > 0, задачи накапливаются быстрее, чем обрабатываются",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(payment_processing_planned_total[1m]) - rate(payment_processing_started_total[1m])",
       "legendFormat": "{{accountName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Payment Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(payment_external_system_request_latency_seconds_bucket[1m])) by (le, accountName))",
     "legendFormat": "p75 {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(payment_external_system_request_latency_seconds_bucket[1m])) by (le, accountName))",
     "legendFormat": "p80 {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.85, sum(rate(payment_external_system_request_latency_seconds_bucket[1m])) by (le, accountName))",
     "legendFormat": "p85 {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(payment_external_system_request_latency_seconds_bucket[1m])) by (le, accountName))",
     "legendFormat": "p90 {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_external_system_request_latency_seconds_bucket[1m])) by (le, accountName))",
     "legendFormat": "p95 {{accountName}}"
    }
   ]
  }
 ]
}